apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-buck
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-buck
    app.kubernetes.io/part-of: tkrw-pr712-0075-0016-app
  name: devfile-sample-buck
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-buck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-buck
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0016-tenant/tkrw-pr712-0075-0016-app/devfile-sample-buck@sha256:6eecc489315cc2f70cb4f75d75922e45eac57a873a821ade20c02f55a2e69243
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
